apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31111
      protocol: TCP # default
  selector:
    app: web
# to test it:
# http://localhost:31111/
